# 09-28일 수업 진행

# 배열 

In [3]:
import numpy as np

In [5]:
x = np.array([1,4,3,5,2])

In [6]:
x.ndim

1

In [14]:
x.shape

(5,)

In [8]:
x.shape

(5,)

In [9]:
print(x)

[1 4 3 5 2]


In [10]:
y = np.array([[1,2,3],[4,6,7]])

In [13]:
print(y.ndim, y.shape)

2 (2, 3)


# 배열 슬라이싱(slicing)

In [15]:
x[2:4]

array([3, 5])

In [16]:
x[:3]

array([1, 4, 3])

In [17]:
x[::2]

array([1, 3, 2])

In [18]:
x

array([1, 4, 3, 5, 2])

In [22]:
sub_x = x[2:5]

In [24]:
sub_x[0] = 100

In [25]:
sub_x

array([100,   5,   2])

In [26]:
x

array([  1,   4, 100,   5,   2])

- sub_x와 x의 차이 확인 ---- 슬라이싱 할 때 주의

In [28]:
y

array([[1, 2, 3],
       [4, 6, 7]])

In [29]:
y[1:2, 2:3]

array([[7]])

## 행렬 구분

In [30]:
y[0, :]

array([1, 2, 3])

In [31]:
y[:, 0]

array([1, 4])

# 배열의 형상(shape)변경

In [32]:
grid = np.arange(1, 10).reshape((3,3))

In [33]:
grid

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [34]:
z = np.array([1,2,3])

In [35]:
z

array([1, 2, 3])

In [36]:
z2 = z.reshape((3,1))

In [37]:
z2

array([[1],
       [2],
       [3]])

In [38]:
z2.shape

(3, 1)

In [39]:
z

array([1, 2, 3])

In [40]:
z.reshape((1,3))

array([[1, 2, 3]])

In [41]:
z

array([1, 2, 3])

In [42]:
z.reshape((3,1))

array([[1],
       [2],
       [3]])

# 배열 연결

In [43]:
x = np.array([1,2,3])

In [44]:
y = np.array([4,5,6])

In [45]:
x + y

array([5, 7, 9])

# 실습 -- 각각의 방식마다 장.단점 존재

### np.concatenate 루틴: array를 인수로 한다

In [46]:
x = np.array([1,2,3])

In [47]:
y = np.array([3,2,1])

In [50]:
np.concatenate([x,y]) #결합

array([1, 2, 3, 3, 2, 1])

In [51]:
grid = np.array([[4,5,6],[7,8,9]])

In [52]:
grid

array([[4, 5, 6],
       [7, 8, 9]])

In [53]:
np.concatenate([grid, grid]) #행(axis = 0) 결합

array([[4, 5, 6],
       [7, 8, 9],
       [4, 5, 6],
       [7, 8, 9]])

In [55]:
np.concatenate([grid, grid],axis= 1) #행(axis = 1) 결합 

array([[4, 5, 6, 4, 5, 6],
       [7, 8, 9, 7, 8, 9]])

### np.vstack,  np.hstack루틴: array리스트를 인수로 한다

In [62]:
x

array([1, 2, 3])

In [57]:
np.vstack([x, grid]) #수직으로 쌓기

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [59]:
z = np.array([[99],[99]])

In [60]:
z

array([[99],
       [99]])

In [61]:
np.hstack([grid, z]) #수평으로

array([[ 4,  5,  6, 99],
       [ 7,  8,  9, 99]])

### np.r_ && np.c_ 루틴: 배열을 각각

In [63]:
a = np.full((2,2),1)

In [64]:
b = np.full((2,2), 2)

In [65]:
a, b

(array([[1, 1],
        [1, 1]]),
 array([[2, 2],
        [2, 2]]))

In [68]:
np.r_[a,b]

array([[1, 1],
       [1, 1],
       [2, 2],
       [2, 2]])

In [69]:
np.c_[a,b]

array([[1, 1, 2, 2],
       [1, 1, 2, 2]])

### 배열 분할

- np.split, hsplit, vsplit 함수로 구현
- n개의 분할점 => n +1개의 하위 배열 생성

In [70]:
x = [1,2,3,55,6,3,2]

In [71]:
x1,x2,x3 = np.split(x,[3,5])

In [72]:
x1, x2, x3

(array([1, 2, 3]), array([55,  6]), array([3, 2]))

In [73]:
grid = np.arange(16).reshape((4,4))

In [74]:
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [76]:
upper, lower = np.vsplit(grid, [2])

In [77]:
upper

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [78]:
lower

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [79]:
left, right = np.hsplit(grid, [2])

In [80]:
left

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [81]:
right

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])