# 2020-09-23 실습
## Numpy

In [4]:
import numpy as np

빠르고 효율적인 다차원 배열 객체 ndarray -- n차원 배열

 - 파이썬 리트로부터 ndarray 만들기:np.array()함수
 

In [5]:
np.array([3,6,2])

array([3, 6, 2])

In [6]:
my_array = np.array([1,2,3])

In [7]:
print(my_array)

[1 2 3]


In [8]:
type(my_array)

numpy.ndarray

In [10]:
b = np.array([3,6,9], dtype = float)

In [11]:
b


array([3., 6., 9.])

In [12]:
array2 = np.array([[1,2],[4,7]])

In [13]:
print(array2)

[[1 2]
 [4 7]]


 - ndarray 객체의 차원: ndim 속성입력

In [14]:
array2.ndim 


2

In [15]:
b.shape

(3,)

In [16]:
array2.shape

(2, 2)

 - 행렬의 크기 및 형태 .shape

In [17]:
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [18]:
np.ones((3,5), dtype=float) 


array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [19]:
np.full((3,5), 3.14) 

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [20]:
np.arange(0, 20, 2) 

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [21]:
np.linspace(0, 2, 5)

array([0. , 0.5, 1. , 1.5, 2. ])

In [22]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [23]:
np.random.seed(0)

In [24]:
np.random.random((3,3))

array([[0.5488135 , 0.71518937, 0.60276338],
       [0.54488318, 0.4236548 , 0.64589411],
       [0.43758721, 0.891773  , 0.96366276]])

In [25]:
np.random.random((4,3))

array([[0.38344152, 0.79172504, 0.52889492],
       [0.56804456, 0.92559664, 0.07103606],
       [0.0871293 , 0.0202184 , 0.83261985],
       [0.77815675, 0.87001215, 0.97861834]])

In [26]:
np.random.normal(0, 1, (3,3))

array([[-0.18158257,  1.41020463, -0.37447169],
       [ 0.27519832, -0.96075461,  0.37692697],
       [ 0.03343893,  0.68056724, -1.56349669]])

In [28]:
np.random.normal(0, 1, (5,2))

array([[-0.56669762, -0.24214951],
       [ 1.51439128, -0.3330574 ],
       [ 0.04736482,  1.46274045],
       [ 1.53502913,  0.56644004],
       [ 0.14926509, -1.078278  ]])

In [29]:
np.random.randint(0, 10, (3,3)) 

array([[8, 1, 1],
       [7, 9, 9],
       [3, 6, 7]])

In [30]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [31]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [32]:
np.empty(3)

array([1., 1., 1.])

In [33]:
x = np.random.randint(10, size = 6)

In [34]:
print(x)

[2 0 3 5 9 4]


In [35]:
x.shape

(6,)

In [36]:
x.ndim

1

In [37]:
x2 = x[1:2].copy()


In [38]:
x2


array([0])

In [39]:
print(x2)

[0]


In [40]:
grid = np.arange(1, 10).reshape((3,3))

In [41]:
print(grid)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
