# numpy 배열 연산

 - 유니버셜 함수

In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3])

In [3]:
np.add(a, 10)

array([11, 12, 13])

In [4]:
a + 10

array([11, 12, 13])

In [5]:
a = np.ones((3,3))

In [7]:
b = np.arange(3)

In [8]:
a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [9]:
b

array([0, 1, 2])

In [10]:
a + b

array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])

## 브로드캐스팅

- test1

In [14]:
test1 = np.arange(3)

In [18]:
test1

array([0, 1, 2])

In [15]:
test1 + 5

array([5, 6, 7])

- test2

In [19]:
test2 = np.ones((3,3)) 

In [20]:
test2

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [17]:
test2 + test1

array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])

- test3 -- 순간 햇갈림

In [21]:
test3 = np.arange(3).reshape((3,1))

In [22]:
test3

array([[0],
       [1],
       [2]])

In [23]:
test3 + test1

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

## 실습 2

In [28]:
np.random.seed(0) #실습 위해 랜덤 값 고정

In [26]:
x = np.random.random(10) #0~1

In [27]:
x

array([0.5488135 , 0.71518937, 0.60276338, 0.54488318, 0.4236548 ,
       0.64589411, 0.43758721, 0.891773  , 0.96366276, 0.38344152])

#### 일반 sum보다 np.sum이 빠르다(중요)

In [29]:
sum(x) 

6.157662833145425

In [31]:
np.sum(x)

6.157662833145425

 - 속도 측정

In [34]:
%time sum(np.random.random(10000))

Wall time: 1.99 ms


4952.396211854349

In [37]:
%time np.sum(np.random.random(10000))

Wall time: 0 ns


4998.538115962798

- 실행시간과 테스트 반복 횟수 확인

In [40]:
%timeit sum(np.random.random(10000))

1.81 ms ± 98 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [39]:
%timeit np.sum(np.random.random(10000))

93.7 µs ± 1.56 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


### 활용

In [43]:
x

array([0.5488135 , 0.71518937, 0.60276338, 0.54488318, 0.4236548 ,
       0.64589411, 0.43758721, 0.891773  , 0.96366276, 0.38344152])

In [41]:
np.mean(x)

0.6157662833145425

In [42]:
np.max(x)

0.9636627605010293

In [45]:
np.nansum(x) #결측값은 제외하고 계산

6.157662833145425

In [48]:
y = np.array([[1,2],[3,4]])

In [49]:
y

array([[1, 2],
       [3, 4]])

In [50]:
np.sum(y)

10

In [52]:
np.max(y)

4

- 행, 열 계싼

In [53]:
np.sum(y, axis = 0)

array([4, 6])

In [54]:
np.sum(y, axis = 1)

array([3, 7])

## 실습3 - 백터화(데이터 표준화)

In [55]:
x = np.random.randint(0, 100,(10,2))

In [56]:
x

array([[74, 13],
       [46,  9],
       [36, 55],
       [62, 29],
       [75, 70],
       [60, 91],
       [72, 15],
       [72, 53],
       [78, 72],
       [73, 50]])

- 각 행의 평균

In [57]:
avgs = np.mean(x, 0) #각 행의 평균(세로 계산)

In [58]:
avgs

array([64.8, 45.7])

In [67]:
avgs1 = np.mean(x,1) #각 열 계싼

In [68]:
avgs1

array([43.5, 27.5, 45.5, 45.5, 72.5, 75.5, 43.5, 62.5, 75. , 61.5])

- 각 행의 표준 편차

In [59]:
sds = np.std(x, 0)

In [60]:
sds #각 행의 표준 편차(세로 계산)

array([13.2196823, 26.7022471])

In [61]:
z = (x - avgs) / sds

In [75]:
z.mean(0)

array([ 1.99840144e-16, -1.16573418e-16])

In [64]:
z.std(0)

array([1., 1.])

In [65]:
z

array([[ 0.695932  , -1.22461604],
       [-1.42212192, -1.37441616],
       [-2.17856975,  0.34828529],
       [-0.21180539, -0.62541553],
       [ 0.77157679,  0.91003577],
       [-0.36309496,  1.69648644],
       [ 0.54464244, -1.14971597],
       [ 0.54464244,  0.27338523],
       [ 0.99851114,  0.98493583],
       [ 0.62028722,  0.16103514]])

In [71]:
x.reshape(2,10)

array([[74, 13, 46,  9, 36, 55, 62, 29, 75, 70],
       [60, 91, 72, 15, 72, 53, 78, 72, 73, 50]])

### 조건(인덱싱)

In [72]:
a = np.arange(10)

In [73]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [74]:
a < 5

array([ True,  True,  True,  True,  True, False, False, False, False,
       False])

In [76]:
a[a<5]

array([0, 1, 2, 3, 4])

In [77]:
a[a%3==0] #부울 마스킹

array([0, 3, 6, 9])

In [78]:
a[[4,2,6]] #팬시 인덱싱

array([4, 2, 6])

### 행렬 곱

In [80]:
x = np.array([[1,2,],[3,4]])

In [81]:
y = np.ones((2,2))

In [83]:
x


array([[1, 2],
       [3, 4]])

In [84]:
y

array([[1., 1.],
       [1., 1.]])

In [85]:
x * y

array([[1., 2.],
       [3., 4.]])

In [87]:
x @ y #행렬 곱

array([[3., 3.],
       [7., 7.]])